version: "2"

services:
  jikan-rest-api:
    build:
      context: jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
    ports:
      - "9080:8080"
    networks:
      - default
    restart: unless-stopped

  jikan-redis:
    image: redis
    restart: unless-stopped
